name: Code Quality

on: [push, pull_request]

jobs:
  ruff:
    name: Lint and Format Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Install dependencies
      run: uv sync --dev

    - name: Run Ruff linter
      run: uv run ruff check . --output-format=github

    - name: Run Ruff formatter check
      run: uv run ruff format --check .
